[package]
name = "rgit"
version = "0.1.0"
authors = ["Erkan <erkan808987@gmail.com>"]
edition = "2018"


[dependencies]
clap = "3.0.0-beta.1"
chrono = "0.4.11"
sha2 = "0.8.1"
bincode = "1.2.1"
serde = {version = "1.0.110",features = ["derive"]}
subprocess = "0.2.4"
nohash-hasher = "0.2.0"
